/**
 *  import-carbon.ts
 *
 *  Import EN 15804 life-cycle carbon (GWP) data from ÖKOBAUDAT into materials.json.
 *
 *  ÖKOBAUDAT is the German government's EPD database, served over a soda4LCA API in the
 *  ILCD+EPD format. Every number this script writes comes from a published, third-party
 *  verified EPD and is stored with its dataset UUID, version and URL — unlike the
 *  physical properties in generate-data.ts, NOTHING here is generated by a model.
 *
 *  Matching is deliberately NOT automatic. EPD names are German, product-specific and
 *  brand-heavy ("binderholz Brettschichtholz BSH"); fuzzy-matching them to our generic
 *  English material names would quietly attach the wrong dataset to the right name,
 *  which is worse than having no data. So CARBON_MAP below is hand-curated, and the
 *  --search mode exists to make extending it cheap.
 *
 *  Run:
 *    npm run import:carbon                 # import everything in CARBON_MAP
 *    npm run import:carbon -- douglas oak  # only these materials
 *    npm run import:carbon -- --search Brettschichtholz   # find UUIDs to add to the map
 *    npm run import:carbon -- --unmapped   # list materials with no dataset yet
 */

import './env.js';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONFIG } from './config.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const DB_PATH = resolve(HERE, CONFIG.output.databaseFile);

const BASE = 'https://oekobaudat.de/OEKOBAU.DAT/resource';
const DATASET_NAME = 'ÖKOBAUDAT';

/**
 * Hand-curated material name → ÖKOBAUDAT dataset UUID.
 *
 * Prefer, in order: EN 15804+A2 compliance, an "average"/generic dataset over a single
 * manufacturer's, a recent reference year, and a validUntil that has not passed.
 * Use `--search` to find candidates, and check the dataset's classification really
 * describes the material before adding it here.
 */
export const CARBON_MAP: Record<string, { uuid: string; note?: string }> = {
    // — mineral —
    concrete:    { uuid: 'b3fb0ba9-2376-49bf-b21a-7f7a5cd97233', note: 'Beton der Druckfestigkeitsklasse C30/37' },
    cement:      { uuid: '87371640-546c-4d9c-84cc-c13b6be94146', note: 'Portlandzement CEM I' },
    sand:        { uuid: '286b0072-1001-4e5f-baa2-282230755243', note: 'Sand 0/2' },
    gravel:      { uuid: 'd35a5f2a-d72c-41a3-9f64-ea1b1ec066d1', note: 'Kies (Korngröße 2/32)' },
    mortar:      { uuid: '7c0535db-e6d1-4342-871d-74cde862d97a', note: 'Mauermörtel (Leichtmauermörtel) — the only non-template masonry mortar dataset' },

    // — stone. ÖKOBAUDAT has no species-specific granite/limestone/sandstone EPDs; it
    //   declares generic "hard" and "soft" natural-stone slabs, which is what these map to.
    stone:       { uuid: 'f82e3ab8-d7bb-4765-a60c-bfe78ede1565', note: 'Natursteinplatte, hart (80 mm)' },
    granite:     { uuid: 'f82e3ab8-d7bb-4765-a60c-bfe78ede1565', note: 'generic HARD natural stone — no granite-specific EPD' },
    marble:      { uuid: '03ed395a-bc7b-4287-9013-8ba3ac1a2900', note: 'Marmorplatte' },
    limestone:   { uuid: 'b3e4257b-bdb7-4da2-9c33-990243dd4aa8', note: 'generic SOFT natural stone — no limestone-specific EPD' },
    sandstone:   { uuid: 'b3e4257b-bdb7-4da2-9c33-990243dd4aa8', note: 'generic SOFT natural stone — no sandstone-specific EPD' },
    slate:       { uuid: '909a1f8a-00d8-436f-86f9-77e0ee840a88', note: 'Schieferplatten' },

    // — masonry —
    bricks:      { uuid: '30514538-fcb4-483b-b5d5-c108d2037536', note: 'Mauerziegel (ungefüllt)' },
    blocks:      { uuid: 'cc0d7baa-755a-4a4a-baf3-4fe53d68a041', note: 'Kalksandstein' },
    terracotta:  { uuid: 'a6d60a75-7a4e-4dfc-87cc-fd40f68d279a', note: 'Dachziegel' },

    // — metal —
    steel:       { uuid: '04d1311a-ae38-4bfb-8e11-8992f1ddb14f', note: 'Baustahl: Grobblech' },
    rebar:       { uuid: 'f6861618-5a92-4c3a-94ba-9f7329b29662', note: 'Bewehrungsstahl' },
    aluminum:    { uuid: '143a4df2-563e-4ef9-b75b-90e1cf9f7ef9', note: 'Aluminiumblech' },
    copper:      { uuid: 'e5a4ebf9-0e5c-4fd8-bb04-1acb5497312f', note: 'Kupferbleche' },
    zinc:        { uuid: '26353b00-6cd3-426d-903b-9fc5b1670398', note: 'Zinkblech' },
    lead:        { uuid: '8aef9045-4b5f-4362-954f-2edda71f63e6', note: 'Bleibleche' },
    iron:        { uuid: 'aa089b30-7862-4001-9286-9cb41058dba0', note: 'ductile cast iron (pipe) — no generic cast-iron EPD' },

    // — glass —
    glass:       { uuid: 'a835bc20-b9fe-4112-bf74-32caa85712c8', note: 'Flachglas, Einscheibensicherheitsglas' },

    // — wood —
    softwood:    { uuid: '7aba3603-0689-4da5-8d24-fd92ae398d07', note: 'Konstruktionsvollholz (Durchschnitt DE)' },
    hardwood:    { uuid: 'e131431f-4d99-4d7a-ae0a-744a06de3524', note: 'Laubschnittholz - getrocknet (Durchschnitt DE)' },
    douglas:     { uuid: '2bd4c91f-16e5-4e01-b8b5-0c01aac363ce', note: 'Nadelschnittholz - getrocknet — no species-specific EPD' },
    plywood:     { uuid: '6bb6bd94-d9a8-4174-a8f3-f1625cbeb118', note: 'Furniersperrholz (Durchschnitt DE)' },
    osb:         { uuid: '766ea5bd-3f0f-4d48-a399-9c4a372524d8', note: 'EGGER OSB-Platten (EU-27)' },
    glulam:      { uuid: '78bfe151-3cf3-46cb-a1a5-61a79bbd5476', note: 'Brettschichtholz - Standardformen (Durchschnitt DE)' },
    clt:         { uuid: '8c4eb262-9ae6-4ace-8f3d-0b06f2007f3e', note: 'Brettsperrholz (Durchschnitt DE)' },

    // — plastic —
    pvc:         { uuid: '0c97fb5f-67df-495e-bac5-f5d931f58a90', note: 'rigid PVC profile (cable trunking) — no bulk-resin EPD' },
    hdpe:        { uuid: '937cf1c5-c813-4778-90e2-6f1ae84c4aa7', note: 'PE pipe systems — no bulk-resin EPD' },

    // — insulation —
    eps:         { uuid: '757297f1-9325-4df4-af51-96510be76bf3', note: 'EPS-Hartschaum (Rohdichte 20 kg/m³, weiß)' },
    xps:         { uuid: 'c4ddfdbc-ee2b-4dd5-a754-b317cf06470a', note: 'Extrudierter Polystyrol Dämmstoff (XPS)' },
    mineralwool: { uuid: '155a3b83-ed73-4462-a4f1-69ce64e24981', note: 'Mineralwolle-Dämmstoff, hoher Rohdichtebereich' },

    // — finish —
    drywall:     { uuid: '0773f90c-78ef-4727-a966-3b005c1a1469', note: 'Gipsplatte nach DIN EN 520 / DIN 18180' },

    // Deliberately absent — ÖKOBAUDAT has no dataset that honestly describes these:
    //   bamboo, sprayfoam (only PU boards, not in-situ foam), wire, grout.
};

interface AnyRec { [k: string]: any }

/** GET + parse JSON, with a clear error on non-200. */
async function api(path: string): Promise<AnyRec>
{
    const res = await fetch(`${BASE}/${path}`, { headers: { accept: 'application/json' } });
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${path}`);
    return res.json() as Promise<AnyRec>;
}

/** Pick the English (else first) value out of an ILCD multi-language string list. */
function lang(list: any): string
{
    if (!Array.isArray(list)) return String(list ?? '');
    return (list.find((x: AnyRec) => x.lang === 'en') ?? list[0])?.value ?? '';
}

/**
 * Normalise an ILCD module label to our LCAModule keys: 'A1-A3' → 'A1A3'.
 * Split modules like 'D/1' collapse onto their base module.
 */
const MODULE_KEYS = new Set([
    'A1', 'A2', 'A3', 'A1A3', 'A4', 'A5',
    'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7',
    'C1', 'C2', 'C3', 'C4', 'D',
]);

function normalizeModule(m: string): string | null
{
    const key = String(m).split('/')[0].replace(/-/g, '').toUpperCase();
    return MODULE_KEYS.has(key) ? key : null;
}

/** Extract {module: value} for one LCIA indicator's `other.anies` block. */
function modulesOf(result: AnyRec): Record<string, number>
{
    const out: Record<string, number> = {};
    for (const a of result?.other?.anies ?? [])
    {
        if (a.module === undefined || a.value === undefined) continue;
        const key = normalizeModule(a.module);
        const value = Number(a.value);
        // Absent ≠ zero, but a published explicit 0 is real data — keep it.
        if (key && Number.isFinite(value)) out[key] = value;
    }
    return out;
}

/**
 * Find one LCIA result by its indicator code, e.g. 'GWP-total'.
 *
 * Match the parenthetical code, not the prose name: the prose differs between dataset
 * generations ("Global Warming Potential total" vs "Global Warming Potential - total")
 * and some datasets carry German only, so any name-substring match silently finds
 * nothing for a large share of the database.
 */
function indicator(doc: AnyRec, code: string): AnyRec | undefined
{
    return (doc?.LCIAResults?.LCIAResult ?? []).find((r: AnyRec) =>
        (r?.referenceToLCIAMethodDataSet?.shortDescription ?? [])
            .some((s: AnyRec) => String(s?.value ?? '').includes(`(${code})`)));
}

/** The declared (reference) flow: its unit, amount and the EPD's own gross density. */
function declaredFlow(doc: AnyRec): { unit: string; amount: number; density?: number }
{
    const refIds: number[] = doc?.processInformation?.quantitativeReference?.referenceToReferenceFlow ?? [0];
    const exchanges: AnyRec[] = doc?.exchanges?.exchange ?? [];
    const flow = exchanges.find(e => refIds.includes(e.dataSetInternalID)) ?? exchanges[0];

    const prop = (flow?.flowProperties ?? []).find((p: AnyRec) => p.referenceFlowProperty)
        ?? flow?.flowProperties?.[0];
    const dens = (flow?.materialProperties ?? []).find(
        (p: AnyRec) => /gross density|bulk density|density/i.test(p.name ?? ''));

    return {
        unit: prop?.referenceUnit ?? 'kg',
        amount: Number(prop?.meanValue ?? flow?.meanAmount ?? 1) || 1,
        density: dens ? Number(dens.value) || undefined : undefined,
    };
}

/** Compliance label ('EN 15804+A2' / '+A1') declared by the dataset. */
function standardOf(doc: AnyRec): 'EN 15804+A2' | 'EN 15804+A1'
{
    const json = JSON.stringify(doc?.modellingAndValidation?.complianceDeclarations ?? {});
    return /\+A2/.test(json) ? 'EN 15804+A2' : 'EN 15804+A1';
}

/** Build the `lca` block for one material from a fetched dataset. */
function lcaBlockFor(doc: AnyRec, uuid: string): AnyRec | null
{
    const total = indicator(doc, 'GWP-total');
    if (!total) return null;

    const flow = declaredFlow(doc);
    const unitNote = `per ${flow.amount} ${flow.unit}`;
    const asProperty = (v: number) => ({ value: v, unit: 'kgCO2e', description: unitNote });

    const modules = Object.fromEntries(
        Object.entries(modulesOf(total)).map(([k, v]) => [k, asProperty(v)]));
    if (!Object.keys(modules).length) return null;

    const bio = indicator(doc, 'GWP-biogenic');
    const biogenic = bio
        ? Object.fromEntries(Object.entries(modulesOf(bio)).map(([k, v]) => [k, asProperty(v)]))
        : undefined;

    const info = doc?.processInformation?.dataSetInformation ?? {};
    const time = doc?.processInformation?.time ?? {};

    return {
        standard: standardOf(doc),
        indicator: 'GWP-total',
        declaredUnit: flow.unit,
        declaredUnitValue: flow.amount,
        ...(flow.density
            ? { density: { value: flow.density, unit: 'kg/m3', description: 'gross density declared by the EPD' } }
            : {}),
        modules,
        ...(biogenic && Object.keys(biogenic).length ? { biogenic } : {}),
        source: {
            dataset: DATASET_NAME,
            uuid,
            version: doc?.version ?? info?.dataSetVersion ?? 'unknown',
            url: `${BASE}/processes/${uuid}?format=html`,
            retrieved: new Date().toISOString().slice(0, 10),
            ...(time?.dataSetValidUntil ? { validUntil: String(time.dataSetValidUntil) } : {}),
        },
    };
}

/**
 * Cradle-to-gate carbon per kg, for the flat `carbon` summary field.
 * Returns undefined when the declared unit cannot be converted to mass — better no
 * number than one derived from a guessed density.
 */
function embodiedPerKg(lca: AnyRec, fallbackDensity?: number): number | undefined
{
    const a13 = lca.modules.A1A3?.value
        ?? ((lca.modules.A1 && lca.modules.A2 && lca.modules.A3)
            ? lca.modules.A1.value + lca.modules.A2.value + lca.modules.A3.value
            : undefined);
    if (a13 === undefined) return undefined;

    const per = a13 / (lca.declaredUnitValue ?? 1);
    // ÖKOBAUDAT mixes SI symbols with German abbreviations: 'qm' is m², 'cbm' is m³.
    // Keep this list in sync with declaredUnitKind() in MaterialManager.ts.
    const unit = String(lca.declaredUnit).trim().toLowerCase();
    if (unit === 'kg') return per;
    if (['m3', 'm^3', 'm³', 'cbm'].includes(unit))
    {
        const density = lca.density?.value ?? fallbackDensity;
        return density ? per / density : undefined;
    }
    return undefined; // m2/qm, piece, … depend on a thickness/size we do not know
}

//// MODES ////

async function search(term: string)
{
    const q = new URLSearchParams({ search: 'true', name: term, format: 'json', pageSize: '20' });
    const res = await api(`processes?${q}`);
    const rows: AnyRec[] = res.data ?? [];
    console.log(`${res.totalCount ?? rows.length} match(es) for "${term}" — showing ${rows.length}\n`);
    for (const r of rows)
    {
        const a2 = (r.compliance ?? []).some((c: AnyRec) => /\+A2/.test(c.name ?? ''));
        console.log(`${r.uuid}  ${a2 ? 'A2' : 'A1'}  ${r.geo ?? '--'}  ${r.refYear ?? '????'}→${r.validUntil ?? '????'}  ${r.subType ?? ''}`);
        console.log(`    ${r.name}`);
        console.log(`    ${r.classific ?? ''}\n`);
    }
}

async function importAll(filter: string[])
{
    const db = JSON.parse(readFileSync(DB_PATH, 'utf8'));
    const materials: AnyRec[] = db.materials ?? [];
    let ok = 0, skipped = 0;

    for (const m of materials)
    {
        const entry = CARBON_MAP[m.name];
        if (!entry) continue;
        if (filter.length && !filter.includes(m.name.toLowerCase())) continue;

        process.stdout.write(`- ${m.name} … `);
        try
        {
            const doc = await api(`processes/${entry.uuid}?format=json&view=extended`);
            const lca = lcaBlockFor(doc, entry.uuid);
            if (!lca) { console.log('no GWP-total in dataset'); skipped++; continue; }

            m.lca = lca;
            const perKg = embodiedPerKg(lca, m.density?.value);
            if (perKg !== undefined)
            {
                m.carbon = {
                    value: Number(perKg.toFixed(4)),
                    unit: 'kgCO2e/kg',
                    description: 'Embodied carbon, cradle to gate (A1-A3), GWP-total',
                    source: `${DATASET_NAME} ${entry.uuid}`,
                };
            }
            const mods = Object.keys(lca.modules).join(',');
            console.log(`ok (${lca.standard}, ${mods}${perKg !== undefined ? `, ${perKg.toFixed(3)} kgCO2e/kg` : ', per-kg n/a'})`);
            ok++;
        }
        catch (e) { console.log(`FAILED (${(e as Error).message})`); skipped++; }
    }

    writeFileSync(DB_PATH, JSON.stringify(db, null, 2) + '\n');
    console.log(`\n${ok} imported, ${skipped} skipped. Patched ${DB_PATH}`);
}

function unmapped()
{
    const db = JSON.parse(readFileSync(DB_PATH, 'utf8'));
    const missing = (db.materials ?? []).filter((m: AnyRec) => !CARBON_MAP[m.name]);
    console.log(`${missing.length} material(s) without a dataset:\n`);
    for (const m of missing) console.log(`  ${m.group.padEnd(11)} ${m.name}`);
    console.log(`\nFind UUIDs with:  npm run import:carbon -- --search <german term>`);
}

async function main()
{
    if (!existsSync(DB_PATH)) { console.error(`No materials.json at ${DB_PATH}`); process.exit(1); }

    const args = process.argv.slice(2);
    const si = args.indexOf('--search');
    if (si !== -1) return search(args.slice(si + 1).join(' '));
    if (args.includes('--unmapped')) return unmapped();
    return importAll(args.map(s => s.toLowerCase()));
}

main().catch((e) => { console.error(e); process.exit(1); });
