
FROM node:22-alpine 

RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
WORKDIR /app

# Install pnpm and tsx globally
RUN npm install -g pnpm tsx

ENV NODE_ENV=production

WORKDIR /app
COPY tsconfig.json ./
COPY src/ ./src/

# Only copy production dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

EXPOSE 4000
CMD ["tsx", "src/ApiServer.ts"]