# Use official Node.js 22 image
FROM node:22-alpine

# Install build dependencies for native modules in one layer
RUN apk update && apk upgrade && apk add --no-cache \
    && npm install -g pnpm tsx \
    && rm -rf /var/cache/apk/* \
    && npm cache clean --force

# Set working directory
WORKDIR /app

# Only copy package.json and pnpm-lock.yaml for dependency install
COPY package.json pnpm-lock.yaml ./

# Install all dependencies
RUN pnpm install --no-frozen-lockfile

# Install dependencies for archiyou-core
# enable this if developing archiyou-core
#WORKDIR /app/lib/archiyou-core
#COPY lib/archiyou-core/package*.json ./
#RUN npm install --prefer-offline --no-audit --no-fund --progress=true --loglevel=error

# Copy remaining config files and source code (as root)
WORKDIR /app
COPY tsconfig.json ./
COPY src/ ./src/

#COPY lib/archiyou-core/tsconfig.json ./lib/archiyou-core/
#COPY lib/archiyou-core/src ./lib/archiyou-core/src/
#COPY lib/archiyou-core/assets ./lib/archiyou-core/assets

# NOTE: src directories might be mounted into the container

COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]

# Expose the port (adjust if needed)
EXPOSE 4000
# Start the API server in development mode
CMD ["tsx", "src/ApiServer.ts"]
