# Basic production stack
# Caddy/proxy, API, redis, worker
#  
# NOTES: 
# - added redis pasword. set it in .env



services:
  # Caddy forward proxy with SSL certs
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # mount in filesystem
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./archiyou-configurator-app/dist:/html
    networks:
      - archiyou-network

  # Redis service (shared by workers)
  redis:
    image: redis:7-alpine
    container_name: archiyou-redis-queue
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    env_file: .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASW}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - archiyou-network

  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: archiyou-api
    ports:
      - "4000"
    env_file: .env # all in local .env file
    environment: # overwrite for docker
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - archiyou-network
    volumes:
      # mount script directory
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    command: sh -c "tsx src/ApiServer.ts 2>&1 | tee /app/logs/api.log"

  # Execution Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: archiyou-worker
    env_file: .env # all in local .env file
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_ID=worker
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'node' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - archiyou-network
    volumes:
      - ./logs:/app/logs
    command: sh -c "tsx src/worker.ts 2>&1 | tee /app/logs/worker.log"

volumes:
  redis_data:
    driver: local

networks:
  archiyou-network:
    driver: bridge
