/**
 * @lit/localize runtime configuration.
 *
 * Import this module once at app startup (before any component uses msg()).
 * Locale can be switched at runtime without a page reload.
 */

import { configureLocalization } from '@lit/localize';

// Generated by `lit-localize build` — will be created after first extract+build
// For now we declare the shape and lazy-load locale modules.
export const { getLocale, setLocale } = configureLocalization({
  sourceLocale: 'en',
  targetLocales: ['nl'],

  loadLocale(locale: string) {
    // Dynamic import of the generated locale module
    return import(`./translations/${locale}.js`);
  },
});

/** Returns the user's preferred locale if it matches a supported locale. */
export function detectLocale(): string {
  const supported = ['en', 'nl'];
  const lang = navigator.language.split('-')[0];
  return supported.includes(lang) ? lang : 'en';
}
