/**
 * ScriptSchema.ts
 *   TypeBox schema for the Script — the central Archiyou data structure.
 *   Single source of truth: the Script class (Script.ts), the server DB model
 *   (apps/server/src/db/schema.ts) and every wire boundary derive from here.
 *
 *   Lives in the package's main src dir (not execution/) so every package can
 *   reach it easily. Param-level schemas stay in execution/schemas.ts; this file
 *   only imports ScriptParamSchema + the param record/preset helpers from there.
 */

import semver from 'semver'
import { Type, type Static, type TLiteral } from 'typebox'

import { ScriptParamSchema, ParamRecordSchema, ParamPresetsSchema } from './execution/schemas'

/**
 * Turn a `readonly [...]` of string literals into the *tuple* of `TLiteral`
 * schemas that `Type.Union` needs to infer a usable union.
 *
 * `CONSTS.map(v => Type.Literal(v))` widens to `TLiteral<...>[]` — an array, not
 * a tuple — and `Static<>` over a union built from a non-tuple resolves to
 * `never`. That is silent: the schema still validates correctly at runtime, but
 * every field typed by it becomes `never` (or `undefined` when Optional), so
 * assigning a perfectly valid licence or delivery value is a type error and the
 * value is unusable in typed code.
 *
 * Keeping the `as const` array as the single source of truth and re-widening the
 * mapped result to a tuple preserves both the runtime schema and the inferred type.
 */
type LiteralTuple<T extends readonly string[]> = { -readonly [K in keyof T]: TLiteral<T[K] & string> }

//// VERSION ////

// @ts-ignore TS2589: TypeBox Refine causes excessively deep type instantiation
export const SemverSchema = Type.Refine(
    Type.String(),
    (value): value is string => semver.valid(semver.coerce(value)) !== null,
    'Expected a valid semver version'
)

//// LICENCES ////

/** Creative Commons 4.0 family (+ CC0). Single source of truth for the licence
 *  vocabulary, reused by the schema and any UI. NOTE: the legacy PublishLicense
 *  union in execution/types.ts uses 'CC BY'-style names and should be reconciled
 *  to reference these SPDX identifiers over time. */
export const CC_LICENCES = [
    'CC0-1.0',
    'CC-BY-4.0',
    'CC-BY-SA-4.0',
    'CC-BY-NC-4.0',
    'CC-BY-ND-4.0',
    'CC-BY-NC-SA-4.0',
    'CC-BY-NC-ND-4.0',
] as const
export type CCLicence = typeof CC_LICENCES[number]
export const CCLicenceSchema = Type.Union(
    CC_LICENCES.map((l) => Type.Literal(l)) as LiteralTuple<typeof CC_LICENCES>,
)

//// SHARED ////

/** Sharing metadata. Present (non-null) means the script is shared. */
export const ScriptSharedSchema = Type.Object({
    created:     Type.String(),                              // ISO string on the wire (Date on the class)
    description: Type.Optional(Type.String()),
    onlyUsers:   Type.Optional(Type.Array(Type.String())),  // User.id[] (see PublicUser.id in @archiyou/types)
    dev:         Type.Optional(Type.Boolean()), // allow access latest dev version under tag :dev  
    licence:     Type.Optional(CCLicenceSchema),
})

//// PUBLISHED ////

/** How a fulfillment's exported files reach the end-user of the configurator. */
export const FULFILLMENT_DELIVERIES = ['anonymous download', 'email', 'pay'] as const
export type FulfillmentDelivery = typeof FULFILLMENT_DELIVERIES[number]
export const FulfillmentDeliverySchema = Type.Union(
    FULFILLMENT_DELIVERIES.map((d) => Type.Literal(d)) as LiteralTuple<typeof FULFILLMENT_DELIVERIES>,
)

/** A fulfillment: a named bundle of outputs (a model, data tables, documents…) the
 *  configurator makes available to end-users, with a delivery method + optional price.
 *  `exports` are output-path strings (see ScriptOutputPath), for example
 *  "default/model/(all)", "default/tables/(name)/xlsx" or "default/docs/(name)/pdf". */
export const ScriptPublishedFulfillmentSchema = Type.Object({
    name:        Type.String(),
    description: Type.Optional(Type.String()),
    exports:     Type.Array(Type.String()),   // resolved output-path strings
    delivery:    FulfillmentDeliverySchema,
    price:       Type.Optional(Type.Number()), // defaults to 0 (applied in UI/normalize)
})

//// TRANSLATIONS ////

/**
 * Machine-generated translations of a published configurator's end-user-facing copy —
 * param labels/descriptions, option labels, group names, preset names, the title,
 * description and details, and the fulfillment names/descriptions.
 *
 * Generated by a background job on the server after publishing (see apps/server's
 * translation queue); the author never triggers or waits for it, and a failure is
 * silent — an untranslated configurator is a perfectly good configurator.
 *
 * `locales` maps locale code → a FLAT map of dotted key → translated string. See
 * i18n/keys.ts for the key grammar and i18n/resolve.ts for how it is read back.
 */
export const ScriptTranslationsSchema = Type.Object({
    /** The language the author actually WROTE in — detected, not assumed. Scripts are
     *  authored in Dutch, German, … just as often as in English, so nothing anywhere
     *  may hardcode 'en' as the source. */
    sourceLocale: Type.String(),
    /** Fingerprint of the source strings these translations were made from, so an
     *  in-place metadata edit can be detected and the set regenerated. */
    sourceHash:   Type.String(),
    /** ISO timestamp of generation. */
    generated:    Type.String(),
    /** Model that produced them, for provenance when quality is questioned. */
    model:        Type.Optional(Type.String()),

    /** NOTE: keyed by Type.String(), NOT by a locale union, deliberately.
     *  Script.fromData() validates this schema on EVERY read, so a strict union would
     *  make one since-removed locale key brick an entire script. Membership is filtered
     *  in the resolver instead, where the cost of an unknown locale is that it is
     *  ignored. */
    locales:      Type.Record(Type.String(), Type.Record(Type.String(), Type.String())),
})

/** Published part of script
 *      Publishing means people can use the configurator.
 *      NOTE: version now lives at the top level of ScriptSchema (shared by
 *      published + shared), not here.
 */
export const ScriptPublishedSchema = Type.Object({
    public:      Type.Optional(Type.Boolean()), // if shown up in lists
    url:         Type.Optional(Type.String()),
    library:     Type.Optional(Type.String()), // library url

    title:       Type.Optional(Type.String()),
    description: Type.Optional(Type.String()),

    licence:     Type.Optional(CCLicenceSchema),
    validated:   Type.Optional(Type.Boolean()), // set once the script has been validated (used later)

    // overrides main params/presets
    params:      Type.Optional(ParamRecordSchema),
    presets:     Type.Optional(Type.Array(Type.String())),

    fulfillments: Type.Optional(Type.Array(ScriptPublishedFulfillmentSchema)),

    // Machine translations of everything above that an end-user reads. Null/absent ⇒
    // the configurator is served in the language it was authored in.
    translations: Type.Optional(Type.Union([Type.Null(), ScriptTranslationsSchema])),
})

//// SCRIPT ////

/**
 *  Defines the schema for a Script
 *   See Script.ts for how the Script works
 */
export const ScriptSchema = Type.Object(
{
    id:          Type.Optional(Type.String()),
    fileId:      Type.Optional(Type.String()), // groups scripts version under one file: created for first script version
    created:     Type.Optional(Type.Union([Type.String(), Type.Null()])),
    updated:     Type.Optional(Type.Union([Type.String(), Type.Null()])),

    name:        Type.Optional(Type.String()),
    author:      Type.Optional(Type.String()), // name of author

    description: Type.Optional(Type.String()),
    details:     Type.Optional(Type.String()),
    tags:        Type.Optional(Type.Array(Type.String())),

    // semver version — nullable: a working/unpublished script has no version.
    // Reused by both `shared` and `published`.
    version:     Type.Optional(Type.Union([Type.Null(), SemverSchema])),

    code:        Type.String(),

    // params are record { <<name>> : ScriptParam }
    params:      Type.Optional(ParamRecordSchema),
    presets:     Type.Optional(ParamPresetsSchema),

    // null or published as
    published:   Type.Optional(Type.Union([Type.Null(), ScriptPublishedSchema])),

    // null or shared as (sharing metadata)
    shared:      Type.Optional(Type.Union([Type.Null(), ScriptSharedSchema])),

    // Main unit system of the script (metric shows mm, imperial shows inches).
    // Presentation preference — does not rescale geometry. Default 'metric'.
    units:       Type.Optional(Type.Union([Type.Literal('metric'), Type.Literal('imperial')])),

    /** Public URL of this version's generated thumbnail (an iso line drawing — see
     *  modeler/SVGExporter.ts), or null when there is none.
     *
     *  Only a URL lives here: the SVG bytes are written to disk by the server and served
     *  as a static file, so library list responses (which already carry every script's
     *  `code`) stay small. Clients never set this — the server stamps it on publish/share
     *  from the SVG sent alongside the script, the same way it stamps `published.url`. */
    thumbnail:   Type.Optional(Type.Union([Type.Null(), Type.String()])),
})

export type ScriptTranslationsData         = Static<typeof ScriptTranslationsSchema>
export type ScriptSharedData               = Static<typeof ScriptSharedSchema>
export type ScriptPublishedData            = Static<typeof ScriptPublishedSchema>
export type ScriptPublishedFulfillmentData = Static<typeof ScriptPublishedFulfillmentSchema>
export type ScriptData                     = Static<typeof ScriptSchema>
