/**
 *  build-wasm.ts
 *  Builds the Rust WASM module and inlines it as a Base64 string into a TypeScript file.
 *
 *  Adapted from packages/meshup/buildscripts/build-wasm.ts. The key property we want from
 *  meshup's approach (and that packages/gdrr2bp-wasm lacks) is that the inlined base64 is
 *  REGENERATED by this script — it is never hand-made — and the wasm-pack glue is actually
 *  committable, so a fresh clone needs no Rust toolchain.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const ROOT_DIR = path.resolve(path.dirname('.')); // from package root
const WASM_DIR = path.join(ROOT_DIR, 'ts', 'wasm');
const OUTPUT_TS_PATH = path.join(ROOT_DIR, 'ts', 'collada-wasm-binary.ts');
const WASM_FILE_NAME = 'collada_wasm_bg.wasm'; // matches the crate name `collada-wasm`

console.log(`**** 🦀 Building COLLADA writer to WASM ****
    In root dir: "${ROOT_DIR}"
    Output TS path: "${OUTPUT_TS_PATH}"
    WASM dir: "${WASM_DIR}"
`);

// 1. Build with wasm-pack. --target web gives us an `init({ module_or_path })` entry point,
//    which is what ts/loader.ts feeds the inlined bytes to.
//    --no-opt: wasm-pack's built-in wasm-opt step was observed respawning wasm-opt in a
//    loop here, so (as packages/meshup/buildscripts/build-wasm.ts also does) we skip it and
//    drive wasm-opt ourselves below, where a failure is non-fatal.
execSync(`wasm-pack build --release --no-opt --target web --out-dir ${WASM_DIR}`, {
    cwd: ROOT_DIR,
    stdio: 'inherit',
});

// 1b. Optimize manually. Optional: the module is small and correct either way, so a missing
//     or failing wasm-opt only costs us some bytes.
const wasmOptBin = (() => {
    const cache = path.join(process.env.HOME || '~', '.cache', '.wasm-pack');
    const dirs = fs.existsSync(cache)
        ? fs.readdirSync(cache).filter(d => d.startsWith('wasm-opt'))
        : [];
    return dirs.map(d => path.join(cache, d, 'bin', 'wasm-opt')).find(p => fs.existsSync(p));
})();

const wasmFilePath = path.join(WASM_DIR, WASM_FILE_NAME);
if (wasmOptBin)
{
    try
    {
        const before = fs.statSync(wasmFilePath).size;
        execSync(`${wasmOptBin} -Os ${wasmFilePath} -o ${wasmFilePath}.opt`, { stdio: 'inherit', timeout: 120_000 });
        fs.renameSync(`${wasmFilePath}.opt`, wasmFilePath);
        const after = fs.statSync(wasmFilePath).size;
        console.log(`[INFO]: wasm-opt ${(before / 1024).toFixed(1)} KB -> ${(after / 1024).toFixed(1)} KB`);
    }
    catch (e)
    {
        console.warn(`[WARN]: wasm-opt failed, shipping the unoptimized module: ${(e as Error).message}`);
        if (fs.existsSync(`${wasmFilePath}.opt`)) { fs.rmSync(`${wasmFilePath}.opt`); }
    }
}
else
{
    console.warn('[WARN]: wasm-opt not found; skipping wasm optimization');
}

// 2. wasm-pack writes a `.gitignore` containing `*` into --out-dir. Remove it so the
//    generated glue can be committed alongside the base64 blob.
// wasm-pack also writes a package.json into --out-dir. A nested manifest inside a published
// package confuses npm about where the package boundary is, and nothing imports ts/wasm as a
// package — loader.ts reaches ./wasm/collada_wasm.js directly.
const outDirManifest = path.join(WASM_DIR, 'package.json');
if (fs.existsSync(outDirManifest))
{
    fs.rmSync(outDirManifest);
    console.log('[INFO]: removed the wasm-pack package.json from ts/wasm/');
}

const outDirGitignore = path.join(WASM_DIR, '.gitignore');
if (fs.existsSync(outDirGitignore))
{
    fs.rmSync(outDirGitignore);
    console.log('[INFO]: removed wasm-pack .gitignore so ts/wasm/ stays committable');
}

// 3. Read the generated .wasm and inline it as base64.
const wasmPath = path.join(WASM_DIR, WASM_FILE_NAME);
const wasmBuffer = fs.readFileSync(wasmPath);
const base64Wasm = wasmBuffer.toString('base64');

const tsContent = `// This file is auto-generated, and used to load WASM directly from base64 string. Do not edit.
export const WASM_BASE64 = "${base64Wasm}";
`;

fs.writeFileSync(OUTPUT_TS_PATH, tsContent);

console.log(`✅ WASM inlined into ${OUTPUT_TS_PATH} (${(wasmBuffer.length / 1024).toFixed(2)} KB)`);
